export const SocketEvents =  {
  /* USER */
  USER_JOINED: 'USER_JOINED',
  USER_LEFT: 'USER_LEFT',
  MY_DATA: 'MY_DATA',
  USER_UPDATED: 'USER_UPDATED',
  /* CALLS */
  REQUESTED_CALL: 'REQUESTED_CALL',
  ACCEPTED_CALL: 'ACCEPTED_CALL',
  DECLINED_CALL: 'DECLINED_CALL',
  CANCEL_CALL: 'CANCEL_CALL',
  /* RTC */
  OFFER: 'OFFER',
  ANSWER: 'ANSWER',
  ICE_CANDIDATE: 'ICE_CANDIDATE',
  /* ERRORS */
  PARSE_ERROR: 'PARSE_ERROR',
  INVALID_EVENT: 'INVALID_EVENT',
  CUSTOM_ERROR: 'CUSTOM_ERROR',
  /* NATIVE */
  CONNECT: 'connection',
  DISCONNECT: 'disconnecting',
};
