export const SocketEvents =  {
  /*  */
  USER_JOINED: 'USER_JOINED',
  USER_LEFT: 'USER_LEFT',
  MY_DATA: 'MY_DATA',
  USER_UPDATED: 'USER_UPDATED',
  /* CALLS */
  REQUESTED_CALL: 'REQUESTED_CALL',
  ACCEPTED_CALL: 'ACCEPTED_CALL',
  DECLINED_CALL: 'DECLINED_CALL',
  GOT_USER_MEDIA: 'DECLINED_CALL',
  CANCEL_CALL: 'CANCEL_CALL',
  /* ERRORS */
  PARSE_ERROR: 'PARSE_ERROR',
  INVALID_EVENT: 'INVALID_EVENT',
};
