export default {
  // INCOMING
  USER_AUTH: 'USER_AUTH',
  ADMIN_AUTH: 'ADMIN_AUTH',
  // SENT
  /* ODMEN */
  REGISTRATION_CONFIRMED: 'REGISTRATION_CONFIRMED',
  /* USER */
  EMAIL_CONFIRMED: 'EMAIL_CONFIRMED',
  USER_BLOCKED: 'USER_BLOCKED',
  CHAT_INVITE: 'CHAT_INVITE',
  CHAT_ACCEPTED: 'CHAT_ACCEPTED',
  NEW_MESSAGE: 'NEW_MESSAGE',
  /* AUTH */
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_FAIL: 'AUTH_FAIL',
  /* ERRORS */
  PARSE_ERROR: 'PARSE_ERROR',
  INVALID_EVENT: 'INVALID_EVENT',
};
